plugins {
    id "java"
    id "io.quarkus"
    id "com.diffplug.spotless"
    id "checkstyle"
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    // quarkus
    implementation enforcedPlatform("io.quarkus.platform:quarkus-bom:${quarkusVersion}")
    implementation "io.quarkus:quarkus-arc"
    implementation "io.quarkus:quarkus-smallrye-health"
    implementation "io.quarkus:quarkus-kubernetes-client"

    // littlehorse
    implementation "io.littlehorse:littlehorse-quarkus:${littlehorseVersion}"

    // logs
    implementation "org.jboss.logging:commons-logging-jboss-logging"
    implementation "org.jboss.logmanager:log4j-jboss-logmanager"
    implementation "org.jboss.slf4j:slf4j-jboss-logmanager"
    implementation "org.jboss.logmanager:log4j2-jboss-logmanager"

    // tests
    testImplementation "io.quarkus:quarkus-junit5"
    testImplementation "io.quarkus:quarkus-test-kubernetes-client"
    testImplementation "io.rest-assured:rest-assured"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

test {
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat = "full"
    }
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
    jvmArgs "--add-opens", "java.base/java.lang=ALL-UNNAMED"
}

compileJava {
    options.encoding = "UTF-8"
    options.compilerArgs << "-parameters"
}

compileTestJava {
    options.encoding = "UTF-8"
}

spotless {
    java {
        removeUnusedImports()
        palantirJavaFormat().style("AOSP")
    }
}

checkstyle {
    configFile = file("${rootDir}/checkstyle.xml")
    checkstyleTest.enabled = false
    checkstyleIntegrationTest.enabled = false
}
