apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lh-kubernetes-connector.fullname" . }}
  labels:
    {{- include "lh-kubernetes-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lh-kubernetes-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lh-kubernetes-connector.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lh-kubernetes-connector.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["{{ .Values.connector.native | ternary "native" "jvm" }}"]
          env:
            - name: QUARKUS_LOG_CATEGORY__IO_LITTLEHORSE__LEVEL
              value: "{{ .Values.connector.logLevel }}"
            - name: QUARKUS_HTTP_PORT
              value: "{{ .Values.connector.port }}"
            - name: LHC_API_HOST
              value: "{{ required "littlehorse.apiHost is missing" .Values.littlehorse.apiHost }}"
            - name: LHC_API_PORT
              value: "{{ required "littlehorse.apiPort is missing" .Values.littlehorse.apiPort }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_DEFAULT_NAMESPACE
              value: "{{ .Values.connector.defaultNamespace }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_APPLY_NAME
              value: "{{ .Values.connector.task.apply.name }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_APPLY_ENABLED
              value: "{{ .Values.connector.task.apply.enabled }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_SECRET_NAME
              value: "{{ .Values.connector.task.secret.name }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_SECRET_ENABLED
              value: "{{ .Values.connector.task.secret.enabled }}"
          ports:
            - name: http
              containerPort: {{ .Values.connector.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
