apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lh-kubernetes-connector.fullname" . }}
  labels:
    {{- include "lh-kubernetes-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lh-kubernetes-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lh-kubernetes-connector.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lh-kubernetes-connector.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["{{ .Values.connector.native | ternary "native" "jvm" }}"]
          env:
            - name: QUARKUS_LOG_CATEGORY__IO_LITTLEHORSE__LEVEL
              value: "{{ .Values.connector.logLevel }}"
            - name: QUARKUS_HTTP_PORT
              value: "{{ .Values.connector.port }}"
            - name: LHC_API_HOST
              value: "{{ required "littlehorse.apiHost is missing" .Values.littlehorse.apiHost }}"
            - name: LHC_API_PORT
              value: "{{ required "littlehorse.apiPort is missing" .Values.littlehorse.apiPort }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_APPLY_NAME
              value: "{{ .Values.connector.task.apply.name }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_APPLY_ENABLED
              value: "{{ .Values.connector.task.apply.enabled }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_STATUS_NAME
              value: "{{ .Values.connector.task.status.name }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_STATUS_ENABLED
              value: "{{ .Values.connector.task.status.enabled }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_SECRET_NAME
              value: "{{ .Values.connector.task.secret.name }}"
            - name: LITTLEHORSE_CONNECTOR_KUBERNETES_TASK_SECRET_ENABLED
              value: "{{ .Values.connector.task.secret.enabled }}"
            {{- if .Values.littlehorse.apiProtocol }}
            - name: LHC_API_PROTOCOL
              value: "{{ .Values.littlehorse.apiProtocol }}"
            {{- end }}
            {{- if .Values.littlehorse.tenantId }}
            - name: LHC_TENANT_ID
              value: "{{ .Values.littlehorse.tenantId }}"
            {{- end }}
            {{- if .Values.littlehorse.workerThreads }}
            - name: LHW_NUM_WORKER_THREADS
              value: "{{ .Values.littlehorse.workerThreads }}"
            {{- end }}
            {{- if .Values.littlehorse.oauth.accessTokenUrl }}
            - name: LHC_OAUTH_ACCESS_TOKEN_URL
              value: "{{ .Values.littlehorse.oauth.accessTokenUrl }}"
            {{- end }}
            {{- if .Values.littlehorse.oauth.clientId.secretName }}
            - name: LHC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.littlehorse.oauth.clientId.secretName }}"
                  key: "{{ required "littlehorse.oauth.clientId.secretKey is missing" .Values.littlehorse.oauth.clientId.secretKey }}"
            {{- end }}
            {{- if .Values.littlehorse.oauth.clientSecret.secretName }}
            - name: LHC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.littlehorse.oauth.clientSecret.secretName }}"
                  key: "{{ required "littlehorse.oauth.clientSecret.secretKey is missing" .Values.littlehorse.oauth.clientSecret.secretKey }}"
            {{- end }}
            {{- if .Values.littlehorse.certs.caCert.secretName }}
            - name: LHC_CA_CERT
              value: "/etc/littlehorse/certs/ca-cert/ca.crt"
            {{- end }}
            {{- if .Values.littlehorse.certs.clientCert.secretName }}
            - name: LHC_CLIENT_CERT
              value: "/etc/littlehorse/certs/client-cert/client.crt"
            {{- end }}
            {{- if .Values.littlehorse.certs.clientKey.secretName }}
            - name: LHC_CLIENT_KEY
              value: "/etc/littlehorse/certs/client-key/client.key"
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.connector.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.littlehorse.certs.caCert.secretName .Values.littlehorse.certs.clientCert.secretName .Values.littlehorse.certs.clientKey.secretName }}
          volumeMounts:
            {{- if .Values.littlehorse.certs.caCert.secretName }}
            - name: littlehorse-ca-cert
              mountPath: "/etc/littlehorse/certs/ca-cert"
              readOnly: true
            {{- end }}
            {{- if .Values.littlehorse.certs.clientCert.secretName }}
            - name: littlehorse-client-cert
              mountPath: "/etc/littlehorse/certs/client-cert"
              readOnly: true
            {{- end }}
            {{- if .Values.littlehorse.certs.clientKey.secretName }}
            - name: littlehorse-client-key
              mountPath: "/etc/littlehorse/certs/client-key"
              readOnly: true
            {{- end }}
          {{- end }}
      {{- if or .Values.littlehorse.certs.caCert.secretName .Values.littlehorse.certs.clientCert.secretName .Values.littlehorse.certs.clientKey.secretName }}
      volumes:
        {{- if .Values.littlehorse.certs.caCert.secretName }}
        - name: littlehorse-ca-cert
          secret:
            secretName: "{{ .Values.littlehorse.certs.caCert.secretName }}"
            items:
              - key: "{{ required "littlehorse.certs.caCert.secretKey is missing" .Values.littlehorse.certs.caCert.secretKey }}"
                path: "ca.crt"
        {{- end }}
        {{- if .Values.littlehorse.certs.clientCert.secretName }}
        - name: littlehorse-client-cert
          secret:
            secretName: "{{ .Values.littlehorse.certs.clientCert.secretName }}"
            items:
              - key: "{{ required "littlehorse.certs.clientCert.secretKey is missing" .Values.littlehorse.certs.clientCert.secretKey }}"
                path: "client.crt"
        {{- end }}
        {{- if .Values.littlehorse.certs.clientKey.secretName }}
        - name: littlehorse-client-key
          secret:
            secretName: "{{ .Values.littlehorse.certs.clientKey.secretName }}"
            items:
              - key: "{{ required "littlehorse.certs.clientKey.secretKey is missing" .Values.littlehorse.certs.clientKey.secretKey }}"
                path: "client.key"
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
