# quarkus
quarkus.http.port=9090
quarkus.smallrye-health.root-path=/
quarkus.log.console.json.enabled=false

# littlehorse extension
lhc.api.host=localhost
lhc.api.port=2023

# littlehorse connector tasks
littlehorse.connector.kubernetes.task.apply.name=lh-kubernetes-connector-apply
littlehorse.connector.kubernetes.task.apply.enabled=true
littlehorse.connector.kubernetes.task.secret.name=lh-kubernetes-connector-secret
littlehorse.connector.kubernetes.task.secret.enabled=false
littlehorse.connector.kubernetes.task.status.name=lh-kubernetes-connector-status
littlehorse.connector.kubernetes.task.status.enabled=true
