quarkus.littlehorse.tasks.start.enabled=false
quarkus.littlehorse.tasks.register.enabled=false
quarkus.littlehorse.workflows.register.enabled=false
quarkus.littlehorse.user-tasks.register.enabled=false
quarkus.kubernetes-client.namespace=default
