# quarkus
quarkus.http.port=9090

# kubernetes extension
quarkus.kubernetes-client.namespace=default

# littlehorse extension
lhc.api.host=localhost
lhc.api.port=2023

# littlehorse connector
littlehorse.connector.kubernetes.task.name=lh-kubernetes-connector
