# quarkus
quarkus.http.port=9090
quarkus.smallrye-health.root-path=/

# kubernetes extension
quarkus.kubernetes-client.namespace=${littlehorse.connector.kubernetes.default.namespace}

# littlehorse extension
lhc.api.host=localhost
lhc.api.port=2023

# littlehorse connector
littlehorse.connector.kubernetes.default.namespace=default

# littlehorse connector tasks
littlehorse.connector.kubernetes.task.apply.name=lh-kubernetes-connector-apply
littlehorse.connector.kubernetes.task.apply.enabled=true
littlehorse.connector.kubernetes.task.secret.name=lh-kubernetes-connector-secret
littlehorse.connector.kubernetes.task.secret.enabled=false
