# Set to debug or trace if log4j initialization is failing
status = ERROR

# Root logger level
rootLogger = ERROR, error

# Name of the configuration
name = AgentWorker

# Console root error appender configuration
appender.error.type = Console
appender.error.name = error
appender.error.layout.type = PatternLayout
appender.error.layout.pattern = %d{HH:mm:ss} %highlight{%-5p} %c - %m%n

# Console agent appender configuration
appender.agent.type = Console
appender.agent.name = agent
appender.agent.layout.type = PatternLayout
appender.agent.layout.pattern = %d{HH:mm:ss} %highlight{%-5p}{TRACE=blue} [AGENT] %c - %m%n

# Console lh appender configuration
appender.lh.type = Console
appender.lh.name = lh
appender.lh.layout.type = PatternLayout
appender.lh.layout.pattern = %d{HH:mm:ss} %highlight{%-5p} [LH] %c - %m%n

# Console javalin appender configuration
appender.javalin.type = Console
appender.javalin.name = javalin
appender.javalin.layout.type = PatternLayout
appender.javalin.layout.pattern = %d{HH:mm:ss} %highlight{%-5p} [JAVALIN] %c - %m%n

# Agent logger
logger.agent = ${env:LOG_LEVEL:-INFO}, agent
logger.agent.name = io.littlehorse.agentworker
logger.agent.additivity = false

# LH logger
logger.lh = INFO, lh
logger.lh.name = io.littlehorse.sdk
logger.lh.additivity = false

# Javalin logger
logger.javalin = INFO, javalin
logger.javalin.name = io.javalin
logger.javalin.additivity = false
