services:
  littlehorse:
    image: ghcr.io/littlehorse-enterprises/littlehorse/lh-standalone:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1822/liveness" ]
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    ports:
      - "2023:2023" # LittleHorse Port
      - "8080:8080" # LittleHorse Dashboard Port
