image:
  repository: littlehorse/lh-kubernetes-connector
  tag: latest

connector:
  logLevel: DEBUG
  task:
    secret:
      enabled: true

littlehorse:
  apiHost: littlehorse
  apiPort: 2024

role:
  kind: ClusterRole
  rules:
    - apiGroups: [ "" ]
      resources: [ "secrets" ]
      verbs: [ "get", "list", "watch", "create", "delete", "patch", "update" ]
    - apiGroups: [ "apps" ]
      resources: [ "deployments" ]
      verbs: [ "get", "list", "watch", "create", "delete", "patch", "update" ]

env:
  - name: QUARKUS_LOG_CONSOLE_JSON_ENABLED
    value: "false"
