image:
  repository: littlehorse/lh-kubernetes-connector
  tag: latest

connector:
  logLevel: DEBUG
  native: true
  task:
    apply:
      enabled: true
    secret:
      enabled: true

littlehorse:
  apiHost: littlehorse
  apiPort: 2024

role:
  rules:
    - apiGroups: [ "" ]
      resources: [ "secrets" ]
      verbs: [ "get", "list", "watch", "create", "delete", "patch", "update" ]
    - apiGroups: [ "apps" ]
      resources: [ "deployments" ]
      verbs: [ "get", "list", "watch", "create", "delete", "patch", "update" ]
