# This will set the replicaset count more information can be found at https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/.
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/.
image:
  repository: ghcr.io/littlehorse-enterprises/lh-kubernetes-connector
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # @schema
  # required: false
  # type: string
  # @schema
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/.
# @schema
# required: false
# type: array
# @schema
imagePullSecrets: []

# This is to override the chart name.
# @schema
# required: false
# type: string
# @schema
nameOverride: ""

# This is to override the resources name.
# @schema
# required: false
# type: string
# @schema
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/.
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?.
  automount: true
  # Annotations to add to the service account.
  # @schema
  # required: false
  # type: object
  # @schema
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  # @schema
  # required: false
  # type: string
  # @schema
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/.
# @schema
# required: false
# type: object
# @schema
podAnnotations: {}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/.
# @schema
# required: false
# type: object
# @schema
podLabels: {}

# Pod level security context. More at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/.
# @schema
# required: false
# type: object
# @schema
podSecurityContext: {}

# Container level security context. More at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/.
# @schema
# required: false
# type: object
# @schema
securityContext: {}

# Pod resources. More at https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/.
# @schema
# required: false
# type: object
# @schema
resources: {}

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Assign pod to nodes. More at https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/.
# @schema
# required: false
# type: object
# @schema
nodeSelector: {}

# Node tolerations. More at https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/.
# @schema
# required: false
# type: array
# @schema
tolerations: []

# Node affinity. More at https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity/.
# @schema
# required: false
# type: object
# @schema
affinity: {}

# Settings related to the kubernetes connector.
connector:
  # Log level
  # @schema
  # required: true
  # enum:
  # - ERROR
  # - WARN
  # - INFO
  # - DEBUG
  # - TRACE
  # @schema
  logLevel: INFO
  # REST health check port.
  port: 9090
  # Specifies whether to run the connector using the native build or jvm.
  native: true
  # Specifies which tasks to run.
  task:
    apply:
      name: lh-kubernetes-connector-apply
      enabled: true
    secret:
      name: lh-kubernetes-connector-secret
      enabled: false
    status:
      name: lh-kubernetes-connector-status
      enabled: true

# Settings related to the lh client. More at https://littlehorse.io/docs/server/developer-guide/client-configuration/.
littlehorse:
  # LH bootstrap server.
  apiHost: ""
  # LH bootstrap server port.
  apiPort: 2023
  # LH bootstrap protocol.
  # @schema
  # required: true
  # enum:
  # - PLAINTEXT
  # - TLS
  # @schema
  apiProtocol: PLAINTEXT
  # LH tenant id.
  # @schema
  # required: false
  # type: string
  # @schema
  tenantId: ""
  # Number of worker threads to run.
  workerThreads: 2
  # OAuth configurations.
  # @schema
  # required: false
  # type: object
  # @schema
  oauth:
    # Identity provider access token URL.
    # @schema
    # required: false
    # type: string
    # @schema
    accessTokenUrl: ""
    # Secret with OAuth client id.
    # @schema
    # required: false
    # type: object
    # @schema
    clientId:
      secretName: ""
      secretKey: ""
    # Secret with OAuth client secret.
    # @schema
    # required: false
    # type: object
    # @schema
    clientSecret:
      secretName: ""
      secretKey: ""
  # TLS configurations.
  # @schema
  # required: false
  # type: object
  # @schema
  certs:
    # Secret with Client Cert File.
    # @schema
    # required: false
    # type: object
    # @schema
    clientCert:
      secretName: ""
      secretKey: ""
    # Secret with Client Key Cert File.
    # @schema
    # required: false
    # type: object
    # @schema
    clientKey:
      secretName: ""
      secretKey: ""
    # Secret with CA Cert File.
    # @schema
    # required: false
    # type: object
    # @schema
    caCert:
      secretName: ""
      secretKey: ""

# This is for setting a Role or ClusterRole.
role:
  # Role type. More at https://kubernetes.io/docs/reference/access-authn-authz/rbac/.
  # @schema
  # required: true
  # enum:
  # - Role
  # - ClusterRole
  # @schema
  kind: Role
  # Specifies whether a role should be created.
  create: true
  # The name of the role to use.
  # If not set and create is true, a name is generated using the fullname template.
  # @schema
  # required: false
  # type: string
  # @schema
  name: ""
  # Annotations to add to the role.
  # @schema
  # required: false
  # type: object
  # @schema
  annotations: {}
  # Set rules access for this connector. More at https://kubernetes.io/docs/reference/access-authn-authz/rbac/.
  # @schema
  # required: false
  # type: array
  # @schema
  rules: []
