name: Agent Worker Build
on:
  workflow_dispatch:
  push:
    paths:
      - agent-worker/**
      - .github/workflows/agent-worker-build.yml
    branches:
      - "**"

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 21

      - name: Validate Code Style
        run: ./gradlew spotlessCheck

      - name: Build and Run Tests
        run: ./gradlew build

      - name: Configure git user to push
        run: |
          git config --global user.name "Organization Workflow"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build and publish
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: agent-worker
          dockerfile: Dockerfile
          registry: ecr
          context: agent-worker
          tags: |
            type=sha,prefix=,format=short
            type=sha,prefix=,format=long
            type=ref,event=branch
